#!/usr/bin/env python3
"""Regenerate the "Lessons & downloads" table in README.md from what's on disk.

Discovers every lesson's Markdown source and its PDF so the README never drifts:

  - Lessons 1-2 : root ``LESSON<n>.md``                 (hand-authored)
  - Lessons 3+  : ``lessons/<NN>-slug/README.md``        (live, config-driven)
  - Roadmap     : ``roadmap/LESSON<n>-slug.md``          (planned outlines)
  - PDFs        : ``docs/pdf/LESSON<n>.pdf``             (built by build_lesson_pdfs.py)

The lesson number and title come from each file's ``# Lesson <n> · <title>`` heading, so a
new lesson is picked up automatically — drop the files in, build the PDFs, run this.

Usage::

    python3 tools/sync-readme-downloads.py          # rewrite the section in README.md
    python3 tools/sync-readme-downloads.py --check   # exit 1 if README is out of date (for CI)

The section is delimited by HTML markers; everything between them is generated.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
PDF_DIR = ROOT / "docs" / "pdf"
# Base URL for the published PDFs. Override for a fork / renamed repo / other host, e.g.
#   LESSON_PDF_BASE_URL=https://myfork.github.io/local-ai-lab/pdf python tools/sync-readme-downloads.py
PDF_URL = os.environ.get(
    "LESSON_PDF_BASE_URL", "https://nikolareljin.github.io/local-ai-lab/pdf"
).rstrip("/")

BEGIN = "<!-- BEGIN: lessons-and-downloads (auto-generated by tools/sync-readme-downloads.py — do not edit by hand) -->"
END = "<!-- END: lessons-and-downloads -->"

# (heading number, title) parsed from a "# Lesson N · Title" H1. The separator after the number
# may be a middot, colon, period, hyphen, or en/em dash.
_H1 = re.compile(r"^#\s+Lesson\s+(\d+)\s*[·:.—–\-]\s*(.+?)\s*$")


def _heading(md: Path) -> tuple[int, str] | None:
    for line in md.read_text(encoding="utf-8").splitlines():
        m = _H1.match(line.strip())
        if m:
            return int(m.group(1)), m.group(2).strip()
    return None


def _discover() -> list[dict]:
    """Return one record per lesson, sorted by number."""
    found: dict[int, dict] = {}

    def add(md: Path, kind: str) -> None:
        h = _heading(md)
        if not h:
            print(
                f"  WARN  {md.relative_to(ROOT).as_posix()}: no parseable "
                "'# Lesson <n> · <title>' heading — skipped (absent from the README table)",
                file=sys.stderr,
            )
            return
        num, title = h
        pdf = PDF_DIR / f"LESSON{num}.pdf"
        found[num] = {
            "num": num,
            "title": title,
            "md": md.relative_to(ROOT).as_posix(),
            "pdf": f"LESSON{num}.pdf" if pdf.is_file() else None,
            "kind": kind,  # "live" | "roadmap"
        }

    # Roadmap outlines first, so that if a lesson number exists in BOTH places (a roadmap outline
    # and a live lesson directory), the live source wins — it is scanned after and overwrites the
    # roadmap entry, and the row is marked live rather than 🚧.
    for p in sorted(ROOT.glob("roadmap/LESSON*.md")):
        add(p, "roadmap")
    for p in sorted(ROOT.glob("LESSON[0-9]*.md")):
        add(p, "live")
    for p in sorted(ROOT.glob("lessons/[0-9]*/README.md")):
        add(p, "live")

    return [found[n] for n in sorted(found)]


def _render(lessons: list[dict]) -> str:
    lines = [
        BEGIN,
        "",
        "_This table is generated by [`tools/sync-readme-downloads.py`](./tools/sync-readme-downloads.py)"
        " from the lesson sources on disk — run it after adding a lesson or rebuilding the PDFs._",
        "",
        "| # | Lesson | Guide (Markdown) | PDF | Status |",
        "|---|--------|------------------|-----|--------|",
    ]
    for r in lessons:
        # Full repo-relative path as the label so live lessons don't all read "README.md".
        guide = f"[`{r['md']}`](./{r['md']})"
        pdf = f"[PDF]({PDF_URL}/{r['pdf']})" if r["pdf"] else "—"
        status = "✅ live" if r["kind"] == "live" else "🚧 roadmap"
        lines.append(f"| {r['num']} | {r['title']} | {guide} | {pdf} | {status} |")

    # Non-lesson PDFs (guides and sample corpus) so "all the PDFs" really means all of them.
    lesson_pdfs = {r["pdf"] for r in lessons if r["pdf"]}
    extras = sorted(p.name for p in PDF_DIR.glob("*.pdf") if p.name not in lesson_pdfs)
    if extras:
        labels = {
            "CHEATSHEET.pdf": "AI-for-developers cheat-sheet",
            "INSTALL.pdf": "Install guide (Linux · macOS · Windows)",
            "The_Magic_Turtle_Astronaut.pdf": "Sample document used in Lesson 1's *try it yourself*",
        }
        lines += ["", "**Other PDFs in [`docs/pdf/`](./docs/pdf/):**"]
        for name in extras:
            label = labels.get(name, name)
            lines.append(f"- [`{name}`]({PDF_URL}/{name}) — {label}")

    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"ERROR: markers not found in {README.name}; add the BEGIN/END markers first.",
              file=sys.stderr)
        return 2
    if text.index(END) < text.index(BEGIN):
        print(f"ERROR: END marker precedes BEGIN marker in {README.name}; fix the marker order "
              "before running (rewriting with them reversed would drop content).",
              file=sys.stderr)
        return 2

    block = _render(_discover())
    pre, _, rest = text.partition(BEGIN)
    _, _, post = rest.partition(END)
    new_text = pre + block + post

    if new_text == text:
        print("README downloads section already up to date.")
        return 0
    if check:
        print("README downloads section is OUT OF DATE — run tools/sync-readme-downloads.py.",
              file=sys.stderr)
        return 1
    README.write_text(new_text, encoding="utf-8")
    print(f"Updated the lessons & downloads table in {README.name}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
