#!/usr/bin/env bash
# Regenerate lessons/CURRICULUM.md from the registry (Lessons 1-2 + lessons/NN-*/lesson.json).
# Run this after adding or renaming a lesson, so the index never drifts.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/lessons/CURRICULUM.md"
# `|| true` keeps the substitution from aborting under `set -e` when no
# interpreter exists, so the explicit check below reports it clearly.
py="${PYTHON_BIN:-$(command -v python3 || command -v python || true)}"
[[ -n "$py" ]] || { echo "Python 3 is required (set PYTHON_BIN or install python3)." >&2; exit 1; }

{
  echo "# Curriculum (generated)"
  echo
  echo "_Generated by \`tools/sync-curriculum.sh\` from the lesson registry. Do not edit by hand._"
  echo
  echo "| # | Lesson | Status | Languages |"
  echo "|---|--------|--------|-----------|"
  echo "| 1 | RAG from scratch | working | python, node, csharp |"
  echo "| 2 | MCP servers | working | python, node, csharp |"
  "$py" "$root/tools/lesson.py" list --md
} > "$out"

echo "Wrote $out"
