#!/usr/bin/env bash
# Regenerate lessons/CURRICULUM.md from the registry (Lessons 1-2 + lessons/NN-*/lesson.json).
# Run this after adding or renaming a lesson, so the index never drifts.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/lessons/CURRICULUM.md"
# Resolve Python 3: prefer python3, fall back to python only when it is actually
# Python 3. `|| true` keeps the lookup from aborting under `set -e`.
py="${PYTHON_BIN:-$(command -v python3 || command -v python || true)}"
if [[ -z "$py" ]] || ! "$py" -c 'import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)' 2>/dev/null; then
  echo "Python 3 is required (set PYTHON_BIN or install python3)." >&2; exit 1
fi

{
  echo "# Curriculum (generated)"
  echo
  echo "_Generated by \`tools/sync-curriculum.sh\` from the lesson registry. Do not edit by hand._"
  echo
  echo "| # | Lesson | Status | Languages |"
  echo "|---|--------|--------|-----------|"
  echo "| 1 | RAG from scratch | working | python, node, csharp |"
  echo "| 2 | MCP servers | working | python, node, csharp |"
  "$py" "$root/tools/lesson.py" list --md
} > "$out"

echo "Wrote $out"
